# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Edit _config.yml to set your title!
description: This is where the description of your site will go. You should change it by editing the _config.yml file. It can be as long as you like! Happy blogging... ❤
github_username: jph00

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

#评论系统valine
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  app_id: EU3MDsX1dTRLODJHEXq7Q3II-gzGzoHsz
  app_key: CE6Ctb6mbGip1C1QS1TiwHYW
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 20 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
  highlight: false

